---
- become: true
  hosts: "all"
  name: "Baseline Configuration"
  tasks:
    - name: "Add the user 'htinoco' and add it to 'sudo'"
      user:
        name: "htinoco"
        group: "sudo"

    - name: "Add SSH key to 'htinoco'"
      authorized_key:
        user: "htinoco"
        state: "present"
        key: "{{ lookup('file', pub_key) }}"

    - name: "Wait for apt to unlock"
      become: true
      shell: "while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 10; done;"

    - name: "Install a list of packages"
      apt:
        pkg:
          - "tree"
      become: true
