---
- become: true
  hosts: "all"
  name: "Baseline Configuration"
  vars:
    ntc_user_password: "{{ lookup('env', 'NTC_USER_PASSWORD') }}"

  tasks:
    - name: "Add the user 'ntc' and add it to 'sudo'"
      user:
        name: "ntc"
        groups:
          - "sudo"
          - "nautobot"
        password: "{{ ntc_user_password }}"

    - name: "Add SSH key to 'ntc'"
      authorized_key:
        user: "ntc"
        state: "present"
        key: "{{ lookup('file', pub_key) }}"

    - name: "Wait for apt to unlock"
      become: true
      shell: "while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 10; done;"

    - name: "Install a list of packages"
      apt:
        pkg:
          - "tree"
      become: true

    - name: Baseline
      ansible.builtin.shell: "{{ item }}"
      loop:
        - sed -i -e '$aAllowUsers ntc root' /etc/ssh/sshd_config
        - sed -i "/^[^#]*PasswordAuthentication[[:space:]]no/c\PasswordAuthentication yes" /etc/ssh/sshd_config
        - sudo systemctl restart sshd
        - sed -i -e '$antc  ALL=(ALL) NOPASSWD:ALL' /etc/sudoers
      become: true
