---
version: "3.8"
services:
  test:
    build:
      target: "test"
      context: "."
  cli:
    env_file:
      - ".env"
    build:
      target: "cli"
      context: "."
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      DO_TOKEN: "${DO_TOKEN}"
    volumes:
      - "./:/usr/src/app"
    image: "${COMMIT_IMAGE:-h4ndzdatm0ld/aws-mgmt:latest}"
