---
version: "3.8"
services:
  test:
    build:
      target: "test"
      context: "."
  cli:
    build:
      target: "cli"
      context: "."
    network_mode: "host"
    environment:
      ENV_EXAMPLE: "${ENV_EXAMPLE}"
    volumes:
      - "./:/usr/src/app"
    image: "${COMMIT_IMAGE:-h4ndzdatm0ld/aws-mgmt:latest}"
