---
version: "3.8"
services:
  test:
    build:
      target: "test"
      context: "."
  cli:
    env_file:
      - ".env"
    build:
      target: "cli"
      context: "."
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      DO_TOKEN: "${DO_TOKEN}"
      NTC_USER_PASSWORD: "${NTC_USER_PASSWORD}"
    volumes:
      - "./:/usr/src/app"
    image: "${COMMIT_IMAGE:-h4ndzdatm0ld/cloud-mgmt:latest}"
  terraform:
    env_file:
      - ".env"
    build:
      target: "tform"
      context: "."
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      TF_VAR_DO_TOKEN: "${TF_DO_TOKEN}"
      DO_TOKEN: "${DO_TOKEN}"
      DO_PAT: "${DO_TOKEN}"
      TF_VAR_AWS_ACCESS_KEY_ID: "${TF_VAR_AWS_ACCESS_KEY_ID}"
      TF_VAR_AWS_SECRET_ACCESS_KEY: "${TF_VAR_AWS_SECRET_ACCESS_KEY}"
    volumes:
      - "./:/usr/src/app"
  packer:
    env_file:
      - ".env"
    image: "hashicorp/packer:latest"
    working_dir: "/usr/src/app"
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      PACKER_PLUGIN_PATH: "/usr/src/app/.packer.d/plugins"
    volumes:
      - "./:/usr/src/app"
